import type { AttackModuleData } from './types';

export const KEYWORDS: Record<string, string> = {
  'firewall': 'A digital barrier that blocks unauthorized access to or from a private network.',
  'antivirus': 'Software designed to detect and destroy computer viruses and other malicious software.',
  'encryption': 'The process of converting information into a secret code to prevent unauthorized access.',
  '2fa': 'Two-Factor Authentication. A security method that requires two forms of identification to access an account.',
  'two-factor authentication': 'A security method that requires two forms of identification to access an account.',
  'vpn': 'Virtual Private Network. A tool that creates a secure, encrypted connection over a public network like the internet.',
  'https': 'HyperText Transfer Protocol Secure. The secure version of HTTP, which means all communications between your browser and the website are encrypted.',
  'ad-blocker': 'A program that removes or alters advertising content from a webpage.',
  'sanitizes': 'The process of cleaning user-provided data to prevent malicious code from being stored or displayed.',
  'sandboxing': 'Running a program in an isolated environment to see how it behaves without risking harm to the main system.'
};


export const ATTACK_MODULES: AttackModuleData[] = [
  {
    id: 'phishing',
    title: 'Phishing',
    simpleDefinition: 'A fake message that tricks people into giving passwords or clicking bad links.',
    kidFriendly: "It’s like someone dressing up like your friend to get your secret candy stash.",
    animationSteps: [
      { time: 0, label: 'email-arrives', text: 'An email arrives in the inbox.', microcopy: 'A new message arrives.', focusPoint: { x: 120, y: 105 } },
      { time: 2, label: 'suspicious-link', text: 'It contains a link that looks suspicious and urgent.', microcopy: 'This link looks urgent. Check the sender!', focusPoint: { x: 167, y: 80 } },
      { time: 5, label: 'user-clicks', text: 'The user clicks the link, unknowingly sending a malicious request.', microcopy: 'Hovering first would show the real URL.', focusPoint: { x: 270, y: 100 } },
      { time: 8, label: 'infection', text: 'A virus is downloaded, compromising the computer.', microcopy: 'Malware is installed.', focusPoint: { x: 330, y: 95 } },
      { time: 11, label: 'defense', text: 'A verification shield blocks the malicious link and warns the user.', microcopy: 'Security software blocks the threat.', focusPoint: { x: 220, y: 70 } },
    ],
    defenses: [
      { point: 'Check the Sender', description: 'Always look at the full email address, not just the name.' },
      { point: 'Hover, Don\'t Click', description: 'Move your mouse over links to see the real destination URL.' },
      { point: 'Use 2FA', description: 'Two-Factor Authentication adds an extra layer of security.' },
    ],
    quiz: {
      question: 'What should you do if an email asks for your password?',
      options: ['Share it right away', 'Click the link to verify', 'Ignore it and tell a trusted adult', 'Delete it and forget'],
      correctAnswer: 'Ignore it and tell a trusted adult',
      explanation: 'You should never share your password. Always verify urgent requests through official channels, not by clicking links in the email.',
    },
    miniSim: {
      description: 'You receive three emails. Which one is the phishing attempt?',
      options: [
        { id: 'a', text: 'Email from school with a homework update.', isCorrect: false },
        { id: 'b', text: 'Email from "Your Bank" saying your account is locked. Click here to unlock NOW!', isCorrect: true },
        { id: 'c', text: 'Email from a friend with a funny cat video link.', isCorrect: false },
      ],
      feedback: {
        correct: 'Correct! The urgent language and generic sender name are big clues.',
        incorrect: 'Not quite. Phishing emails often create a sense of urgency to make you act without thinking.',
      },
    },
    funFact: "The term 'phishing' is a play on the word 'fishing,' because criminals are 'fishing' for your personal information.",
    badge: 'Phish Finder',
  },
  {
    id: 'malware',
    title: 'Malware (Viruses / Worms)',
    simpleDefinition: 'Software that harms your computer or steals things.',
    kidFriendly: 'A tiny digital germ that makes your files sick.',
    animationSteps: [
      { time: 0, label: 'download', text: 'A user downloads an unknown file from the internet.', microcopy: 'An unknown file is downloaded.' },
      { time: 3, label: 'execution', text: 'Opening the file releases malware particles into the system.', microcopy: 'This file contains unknown code.' },
      { time: 6, label: 'spread', text: 'The malware multiplies and spreads to other files, corrupting them.', microcopy: 'The malware spreads like a virus.'},
      { time: 9, label: 'damage', text: 'The infected files turn red and become unusable.', microcopy: 'Files are now corrupted!' },
      { time: 12, label: 'defense', text: 'An antivirus scan detects and quarantines the malware, restoring the files.', microcopy: 'Antivirus scans and cleans the system.' },
    ],
    defenses: [
      { point: 'Don\'t Download Unknown Files', description: 'Only download software from trusted websites.' },
      { point: 'Keep Antivirus Updated', description: 'Regular updates help your antivirus software recognize new threats.' },
      { point: 'Scan Attachments', description: 'Use your antivirus to scan email attachments before opening them.' },
    ],
    quiz: {
      question: 'True or False: Antivirus can remove all threats even without being updated.',
      options: ['True', 'False'],
      correctAnswer: 'False',
      explanation: 'Antivirus software needs regular updates to learn about the latest viruses and malware.',
    },
    miniSim: {
      description: 'A scan found three files. Which one should you quarantine?',
      options: [
        { id: 'a', text: 'homework.docx', isCorrect: false },
        { id: 'b', text: 'family_photo.jpg', isCorrect: false },
        { id: 'c', text: 'free_game_installer.exe (Unverified source)', isCorrect: true },
      ],
      feedback: {
        correct: 'Excellent! Executable files from unverified sources are a common way malware spreads.',
        incorrect: 'Be careful! The most suspicious file is usually one that promises something for free and is an executable (.exe).',
      },
    },
    funFact: "The first computer worm, the Morris Worm, was created in 1988 and accidentally infected thousands of computers, slowing them down significantly.",
    badge: 'Malware Master',
  },
  {
    id: 'ransomware',
    title: 'Ransomware',
    simpleDefinition: 'An attack that locks your files and demands payment.',
    kidFriendly: "It’s like a bully locking your locker and asking for candy to open it.",
    animationSteps: [
      { time: 0, label: 'infection', text: 'Malware quietly enters the system, often through phishing.', microcopy: 'A malicious file runs silently.', focusPoint: {x: 180, y: 95} },
      { time: 3, label: 'encryption', text: 'The malware begins to lock files one by one with strong encryption.', microcopy: 'Your files are being locked!', focusPoint: { x: 220, y: 95 } },
      { time: 6, label: 'ransom-note', text: 'A message appears on screen demanding payment to unlock the files.', microcopy: 'Files are locked! Never pay.', focusPoint: { x: 200, y: 100 } },
      { time: 9, label: 'helpless', text: 'The user is locked out of all their important documents.', microcopy: 'Access is blocked.', focusPoint: { x: 200, y: 100 } },
      { time: 12, label: 'defense', text: 'The user restores their files from a backup, ignoring the ransom.', microcopy: 'Restoring from a backup saves the day.', focusPoint: { x: 55, y: 50 } },
    ],
    defenses: [
        { point: 'Regular Backups', description: 'Keep copies of important files on an external drive or in the cloud.' },
        { point: 'Keep Software Updated', description: 'Patches often fix security holes that ransomware exploits.' },
        { point: 'Don\'t Pay the Ransom', description: 'There is no guarantee you will get your files back, and it encourages attackers.' },
    ],
    quiz: {
      question: 'What is the safest first response to a ransomware attack?',
      options: ['Pay the money immediately', 'Try to guess the password', 'Restore files from a backup', 'Turn off the computer'],
      correctAnswer: 'Restore files from a backup',
      explanation: 'Restoring from a clean backup is the most reliable way to recover from ransomware without paying criminals.',
    },
    miniSim: {
      description: 'Your files are locked! What do you do?',
      options: [
        { id: 'a', text: 'Pay the attacker.', isCorrect: false },
        { id: 'b', text: 'Restore from your cloud backup.', isCorrect: true },
        { id: 'c', text: 'Try to delete the ransomware message.', isCorrect: false },
      ],
      feedback: {
        correct: 'Perfect! Using your backup means the attacker has no power over you.',
        incorrect: 'That\'s a risky choice. The best strategy is to have a backup ready so you never have to consider paying.',
      },
    },
    funFact: 'Some ransomware gangs run professional operations with customer support hotlines to help victims pay the ransom!',
    badge: 'Ransom Rescuer',
  },
   {
    id: 'ddos',
    title: 'Denial of Service (DDoS)',
    simpleDefinition: 'Flooding a website with so much traffic that real users can’t use it.',
    kidFriendly: 'Like thousands of fake students crowding the school gate so no one can get into class.',
    animationSteps: [
      { time: 0, label: 'normal-traffic', text: 'A server is handling normal traffic from legitimate users.', microcopy: 'Normal user traffic.', focusPoint: { x: 330, y: 95 } },
      { time: 3, label: 'attack-begins', text: 'A flood of malicious traffic from many sources targets the server.', microcopy: 'Too many requests overload the site.', focusPoint: { x: 200, y: 100 } },
      { time: 6, label: 'overload', text: 'The server becomes overwhelmed and cannot respond to real users.', microcopy: 'The server is slowing down...', focusPoint: { x: 330, y: 95 } },
      { time: 9, label: 'offline', text: 'The website becomes slow or completely unavailable.', microcopy: 'Site offline!', focusPoint: { x: 330, y: 95 } },
      { time: 12, label: 'defense', text: 'A traffic filter is enabled, blocking the malicious traffic and letting real users in.', microcopy: 'Filters can block bad traffic.', focusPoint: { x: 270, y: 100 } },
    ],
    defenses: [
        { point: 'Traffic Filtering', description: 'A Firewall can identify and block malicious traffic before it reaches the server.' },
        { point: 'Rate Limiting', description: 'This limits how many requests a single address can make in a certain time.' },
        { point: 'Content Delivery Network (CDN)', description: 'CDNs distribute traffic across many servers, making it harder to overwhelm any single one.' },
    ],
    quiz: {
      question: 'What happens to a website during a successful DDoS attack?',
      options: ['It gets faster', 'It steals user data', 'It becomes slow or unavailable', 'Nothing happens'],
      correctAnswer: 'It becomes slow or unavailable',
      explanation: 'The goal of a DDoS attack is to overwhelm a service with traffic, making it inaccessible to legitimate users.',
    },
    miniSim: {
      description: 'A DDoS attack is underway! Toggle the traffic filter to protect the server.',
      options: [
        { id: 'a', text: 'Turn Filter ON', isCorrect: true },
        { id: 'b', text: 'Turn Filter OFF', isCorrect: false },
      ],
      feedback: {
        correct: 'Great! The filter is now dropping malicious packets and the server is recovering.',
        incorrect: 'Without the filter, the server will crash! Turn it on to protect the site.',
      },
    },
    funFact: 'In 2018, a DDoS attack was recorded at a massive 1.7 Terabits per second, one of the largest ever.',
    badge: 'Network Protector',
  },
  {
    id: 'mitm',
    title: 'Man-in-the-Middle (MitM)',
    simpleDefinition: 'An attacker secretly listens to or changes messages between two people.',
    kidFriendly: "It’s like a person intercepting and altering a letter before it reaches your friend.",
    animationSteps: [
      { time: 0, label: 'connection', text: 'A user connects to public Wi-Fi to send a message.', microcopy: 'Connecting on public Wi-Fi...' },
      { time: 3, label: 'interception', text: 'An attacker on the same network intercepts the message.', microcopy: 'Public Wi-Fi can be risky.' },
      { time: 6, label: 'alteration', text: 'The attacker reads and changes the message before sending it on.', microcopy: 'The message is being changed!' },
      { time: 9, label: 'deception', text: 'The recipient receives the altered message, not knowing it was changed.', microcopy: 'The wrong information is received.' },
      { time: 12, label: 'defense', text: 'Using a VPN creates an encrypted tunnel, making the data unreadable to the attacker.', microcopy: 'An encrypted lock protects the message.' },
    ],
    defenses: [
        { point: 'Use HTTPS', description: 'Look for the padlock icon in your browser address bar to ensure your connection is encrypted.' },
        { point: 'Use a VPN on Public Wi-Fi', description: 'A Virtual Private Network (VPN) encrypts all your internet traffic.' },
        { point: 'Avoid Sensitive Tasks', description: 'Don\'t log into your bank or email on public networks if you can avoid it.' },
    ],
    quiz: {
      question: 'How does encryption (like HTTPS or a VPN) help prevent MitM attacks?',
      options: ['It makes your internet faster', 'It hides your messages so an interceptor can’t read them', 'It blocks all Wi-Fi signals', 'It deletes your messages'],
      correctAnswer: 'It hides your messages so an interceptor can’t read them',
      explanation: 'Encryption scrambles your data, so even if an attacker intercepts it, they can\'t understand or alter it.',
    },
    miniSim: {
      description: 'You need to check your school grades at a cafe. What should you do?',
      options: [
        { id: 'a', text: 'Connect to the free public Wi-Fi and log in.', isCorrect: false },
        { id: 'b', text: 'Turn on your VPN before using the public Wi-Fi.', isCorrect: true },
        { id: 'c', text: 'Ask the barista for their password.', isCorrect: false },
      ],
      feedback: {
        correct: 'Smart choice! A VPN encrypts your connection, keeping your login details safe on public Wi-Fi.',
        incorrect: 'Be careful! Logging in on unsecured public Wi-Fi could expose your password to an attacker.',
      },
    },
    funFact: 'Tools that can perform MitM attacks are surprisingly easy to find online, which is why being careful on public Wi-Fi is so important!',
    badge: 'Tunnel Guard',
  },
  {
    id: 'sqlinjection',
    title: 'SQL Injection',
    simpleDefinition: 'Tricking a website into giving secret data by typing harmful code into forms.',
    kidFriendly: "Like writing a secret message that makes the school computer give you the answer key.",
    animationSteps: [
      { time: 0, label: 'form-input', text: 'A user types into a search form on a website.', microcopy: 'A normal search...' },
      { time: 3, label: 'malicious-code', text: 'Instead of a name, the attacker types a piece of SQL code.', microcopy: 'This isn\'t a name, it\'s code!' },
      { time: 6, label: 'database-trick', text: 'The website\'s database gets confused and runs the code.', microcopy: 'The database is tricked.' },
      { time: 9, label: 'data-leak', text: 'The database reveals private user data that should be secret.', microcopy: 'Secret data is leaking!' },
      { time: 12, label: 'defense', text: 'An input filter (sanitizer) blocks the malicious code before it reaches the database.', microcopy: 'A sanitizer blocks the harmful code.' },
    ],
    defenses: [
        { point: 'Input Validation', description: 'Websites should check and clean all user inputs to block code.' },
        { point: 'Parameterized Queries', description: 'A secure coding practice that separates code from user data.' },
        { point: 'Keep Databases Patched', description: 'Updating database software fixes security vulnerabilities.' },
    ],
    quiz: {
      question: 'Why should a website check what users type into forms?',
      options: ['To correct spelling mistakes', 'To prevent harmful code from getting in', 'To make the website faster', 'To change the font color'],
      correctAnswer: 'To prevent harmful code from getting in',
      explanation: 'By validating and sanitizing user input, websites can prevent attacks like SQL Injection.',
    },
    miniSim: {
      description: 'You\'re testing a website form. What should you do?',
      options: [
        { id: 'a', text: 'Type special characters like \' and ; to see if it breaks.', isCorrect: false },
        { id: 'b', text: 'Only type normal text as expected.', isCorrect: true },
      ],
      feedback: {
        correct: 'Correct. On real websites, you should always use forms as intended.',
        incorrect: 'While security researchers do this, you should never try to break a real website. It can be illegal!',
      },
    },
    funFact: 'A famous webcomic, xkcd, published a comic about "Little Bobby Tables" which perfectly explains SQL injection in a hilarious way.',
    badge: 'Database Defender',
  },
  {
    id: 'xss',
    title: 'Cross-site Scripting (XSS)',
    simpleDefinition: 'Putting bad code into a website so others see it and get hacked.',
    kidFriendly: "It’s like writing a silly sticker on a classroom whiteboard that makes everyone’s pens stop working.",
    animationSteps: [
      { time: 0, label: 'comment', text: 'An attacker posts a comment on a website.', microcopy: 'Posting a comment...' },
      { time: 3, label: 'hidden-script', text: 'The comment contains a hidden, malicious script.', microcopy: 'This comment contains a hidden script!' },
      { time: 6, label: 'victim-view', text: 'Another user views the page with the malicious comment.', microcopy: 'Another user views the page.' },
      { time: 9, label: 'script-run', text: 'The script runs in the victim\'s browser, stealing their data (like cookies).', microcopy: 'The script steals the user\'s data!' },
      { time: 12, label: 'defense', text: 'The website sanitizes the comment, removing the script before it is displayed.', microcopy: 'The website cleans the comment, removing the script.' },
    ],
    defenses: [
        { point: 'Sanitize User Input', description: 'Websites must clean user-provided data to remove scripts.' },
        { point: 'Content Security Policy (CSP)', description: 'A website can tell browsers which scripts are safe to run.' },
        { point: 'Be Wary of Unexpected Pop-ups', description: 'If a site behaves strangely, close the tab.' },
    ],
    quiz: {
      question: 'In an XSS attack, where does the malicious script run?',
      options: ['On the website\'s server', 'In the attacker\'s computer', 'In the victim\'s web browser', 'In the database'],
      correctAnswer: 'In the victim\'s web browser',
      explanation: 'The danger of XSS is that the website accidentally sends the attacker\'s script to other users, and it runs in their browsers.',
    },
    miniSim: {
      description: 'You see a weirdly formatted comment on a blog with lots of strange text. What do you do?',
      options: [
        { id: 'a', text: 'Copy and paste it to see what it does.', isCorrect: false },
        { id: 'b', text: 'Ignore it and maybe report it to the site owner.', isCorrect: true },
        { id: 'c', text: 'Reply to the comment.', isCorrect: false },
      ],
      feedback: {
        correct: 'Good choice. Ignoring and reporting suspicious content is the safest thing to do.',
        incorrect: 'Pasting unknown code or text can be dangerous! It\'s best to leave it alone.',
      },
    },
    funFact: 'In 2005, the "Samy" worm was an XSS attack that spread across MySpace, gaining over a million "friends" in less than 24 hours.',
    badge: 'Script Shield',
  },
  {
    id: 'password',
    title: 'Password Attacks',
    simpleDefinition: 'Trying many passwords until one works, or reusing leaked passwords.',
    kidFriendly: "Like guessing locker combos until one fits.",
    animationSteps: [
      { time: 0, label: 'login-form', text: 'An attacker targets a user\'s login page.', microcopy: 'A login form.' },
      { time: 3, label: 'brute-force', text: 'Automated software tries thousands of passwords per second.', microcopy: 'Guessing passwords very fast!' },
      { time: 6, label: 'weak-password', text: 'A simple, common password like "123456" is guessed correctly.', microcopy: 'A weak password was found!' },
      { time: 9, label: 'account-breach', text: 'The attacker gains access to the account.', microcopy: 'Account compromised!' },
      { time: 12, label: 'defense', text: 'The account locks after a few failed attempts and requires 2FA.', microcopy: 'Account lockout and 2FA stop the attack.' },
    ],
    defenses: [
        { point: 'Strong, Unique Passwords', description: 'Use a long mix of letters, numbers, and symbols. Don\'t reuse passwords!' },
        { point: 'Password Managers', description: 'They create and remember strong, unique passwords for you.' },
        { point: 'Two-Factor Authentication (2FA)', description: 'Requires a second code (from your phone) to log in.' },
    ],
    quiz: {
      question: 'What is the BEST way to create passwords for different websites?',
      options: ['Use one super-strong password everywhere', 'Use a different, strong password for every site', 'Use your pet\'s name and birthday', 'Write them all on a sticky note'],
      correctAnswer: 'Use a different, strong password for every site',
      explanation: 'Using unique passwords for each site prevents a leak on one site from compromising your other accounts. A password manager helps with this!',
    },
    miniSim: {
      description: 'Which of these is the strongest password?',
      options: [
        { id: 'a', text: 'Password123', isCorrect: false },
        { id: 'b', text: 'jennifer', isCorrect: false },
        { id: 'c', text: 'BlU3-d0g-R@n-F$st!', isCorrect: true },
      ],
      feedback: {
        correct: 'Exactly! Long passwords with a mix of character types are the hardest to crack.',
        incorrect: 'Simple words, names, or number sequences can be guessed by computers very quickly.',
      },
    },
    funFact: 'In the 1990s, a standard computer could try a few thousand passwords per second. Today, specialized hardware can try trillions per second!',
    badge: 'Password Protector',
  },
  {
    id: 'spyware',
    title: 'Spyware',
    simpleDefinition: 'Malware that secretly watches and records what you do on your computer.',
    kidFriendly: "Like a tiny spy hiding in your room, writing down everything you do.",
    animationSteps: [
      { time: 0, label: 'install', text: 'A user installs a free app that secretly includes spyware.', microcopy: 'Spyware hides in other apps.', focusPoint: { x: 200, y: 100 } },
      { time: 3, label: 'observe', text: 'The spyware activates, watching the user\'s screen and camera.', microcopy: 'The camera turns on secretly!', focusPoint: { x: 205, y: 105 } },
      { time: 6, label: 'record', text: 'It records keystrokes and takes screenshots of sensitive information.', microcopy: 'Your actions are being recorded.', focusPoint: { x: 200, y: 100 } },
      { time: 9, label: 'send-data', text: 'The recorded data is sent to the attacker over the internet.', microcopy: 'Your private data is stolen.', focusPoint: { x: 370, y: 40 } },
      { time: 12, label: 'defense', text: 'A good antivirus program detects and removes the spyware.', microcopy: 'Antispyware tools can find and remove it.', focusPoint: { x: 190, y: 80 } },
    ],
    defenses: [
        { point: 'Limit App Permissions', description: 'Only give apps the permissions they absolutely need (e.g., does a game need camera access?).' },
        { point: 'Use an Antivirus with Spyware Protection', description: 'Keep it updated to detect the latest threats.' },
        { point: 'Be Careful with Free Software', description: 'If a product is free, sometimes YOU are the product. Only download from reputable sources.' },
    ],
    quiz: {
      question: 'What is a common way for spyware to get on your computer?',
      options: ['Through a computer update', 'Bundled with other "free" software', 'By using a strong password', 'From the computer store'],
      correctAnswer: 'Bundled with other "free" software',
      explanation: 'Spyware often hitches a ride with other programs, especially free ones from untrustworthy websites.',
    },
    miniSim: {
      description: 'A new game app is asking for permission to access your camera, microphone, and contacts. What should you do?',
      options: [
        { id: 'a', text: 'Accept all permissions to play the game.', isCorrect: false },
        { id: 'b', text: 'Deny the permissions. The game shouldn\'t need them.', isCorrect: true },
        { id: 'c', text: 'Accept now and change it later.', isCorrect: false },
      ],
      feedback: {
        correct: 'Exactly! Questioning why an app needs certain permissions is a great security habit.',
        incorrect: 'Think about what permissions an app really needs. Granting too many can be a privacy risk.',
      },
    },
    funFact: 'Some spyware is marketed as "monitoring software" for parents or employers, blurring the line between security and surveillance.',
    badge: 'Spy Spotter',
  },
   {
    id: 'trojan',
    title: 'Trojan Horse',
    simpleDefinition: 'Malware that looks like a legitimate program but has a hidden, malicious purpose.',
    kidFriendly: "It’s like getting a cool toy that secretly has a monster hidden inside.",
    animationSteps: [
      { time: 0, label: 'disguise', text: 'A program is disguised as a fun game or useful tool.', microcopy: 'Looks like a normal app.', focusPoint: { x: 75, y: 100 } },
      { time: 3, label: 'download', text: 'A user downloads and runs the disguised program.', microcopy: 'The user runs the program.', focusPoint: { x: 275, y: 100 } },
      { time: 6, label: 'hidden-action', text: 'While the user is distracted, the Trojan installs malware in the background.', microcopy: 'Something else is happening secretly!', focusPoint: { x: 70, y: 110 } },
      { time: 9, label: 'backdoor', text: 'The malware creates a "backdoor," giving attackers control of the computer.', microcopy: 'The hacker now has control.', focusPoint: { x: 280, y: 80 } },
      { time: 12, label: 'defense', text: 'A firewall can block the Trojan from communicating with the attacker.', microcopy: 'A firewall blocks unauthorized connections.', focusPoint: { x: 220, y: 110 } },
    ],
    defenses: [
        { point: 'Don’t Trust Pirated Files', description: 'Cracked games and software are common sources of Trojans.' },
        { point: 'Use a Firewall', description: 'A firewall monitors network traffic and can block suspicious connections.' },
        { point: 'Scan Before Running', description: 'Use antivirus to check new programs before you open them.' },
    ],
    quiz: {
      question: 'Why is it called a "Trojan Horse"?',
      options: ['It was invented in Troy', 'It looks like a horse', 'It\'s named after the Greek story where a wooden horse hid soldiers', 'It only infects horse pictures'],
      correctAnswer: 'It\'s named after the Greek story where a wooden horse hid soldiers',
      explanation: 'Just like in the story, the malware tricks you into bringing it inside your defenses by disguising itself as something harmless.',
    },
    miniSim: {
      description: 'You found a website offering a free, pirated version of an expensive video game. What should you do?',
      options: [
        { id: 'a', text: 'Download it to save money.', isCorrect: false },
        { id: 'b', text: 'Avoid it, as it could contain a Trojan or other malware.', isCorrect: true },
        { id: 'c', text: 'Ask a friend to download it for you.', isCorrect: false },
      ],
      feedback: {
        correct: 'Smart move. Pirated software is one of the most common ways Trojans spread.',
        incorrect: 'While it seems tempting, pirated software is a huge security risk. It\'s not worth it!',
      },
    },
    funFact: 'Unlike viruses and worms, Trojans cannot replicate themselves. They rely on users being tricked into running them.',
    badge: 'Trojan Tamer',
  },
  {
    id: 'adware',
    title: 'Adware',
    simpleDefinition: 'Software that automatically displays or downloads unwanted advertisements.',
    kidFriendly: "Like a super annoying ghost that keeps throwing pop-up ads all over your screen.",
    animationSteps: [
      { time: 0, label: 'install', text: 'Adware is secretly bundled with a free software download.', microcopy: 'Adware is installed.' },
      { time: 3, label: 'popups', text: 'The user starts seeing endless pop-up ads while browsing.', microcopy: 'So many pop-ups!' },
      { time: 6, label: 'slowdown', text: 'The ads use up computer resources, making it slow down.', microcopy: 'The computer is getting slow.' },
      { time: 9, label: 'malicious-ads', text: 'Some ads may even link to more dangerous malware.', microcopy: 'These ads can be dangerous!' },
      { time: 12, label: 'defense', text: 'An ad-blocker and a malware scanner can find and remove the adware.', microcopy: 'Ad-blockers and scanners can help.' },
    ],
    defenses: [
        { point: 'Use an Ad-Blocker', description: 'Browser extensions can block most pop-ups and intrusive ads.' },
        { point: 'Read Installation Prompts', description: 'Carefully uncheck any "optional" software offers when installing new programs.' },
        { point: 'Run Adware Scanners', description: 'Specialized tools can find and remove adware programs.' },
    ],
    quiz: {
      question: 'What is the main purpose of adware?',
      options: ['To speed up your computer', 'To show you unwanted ads and make money for the attacker', 'To protect your files', 'To help you shop online'],
      correctAnswer: 'To show you unwanted ads and make money for the attacker',
      explanation: 'Adware generates revenue for its creators by forcing users to see advertisements.',
    },
    miniSim: {
      description: 'You\'re installing a new photo editor. The installer asks if you also want to install a "free search toolbar".',
      options: [
        { id: 'a', text: 'Accept it. More free stuff is always good.', isCorrect: false },
        { id: 'b', text: 'Decline it. It\'s likely unwanted adware.', isCorrect: true },
      ],
      feedback: {
        correct: 'Good job. These "optional" offers are often adware or other potentially unwanted programs (PUPs).',
        incorrect: 'Be careful! These extra offers are rarely useful and often just serve to show you more ads.',
      },
    },
    funFact: 'While very annoying, most adware is not considered as dangerous as other forms of malware like ransomware or spyware.',
    badge: 'Ad Buster',
  },
  {
    id: 'keylogger',
    title: 'Keylogger',
    simpleDefinition: 'A type of spyware that records every key you press on your keyboard.',
    kidFriendly: "Imagine a tiny bug that sits on your keyboard and writes down every letter you type.",
    animationSteps: [
      { time: 0, label: 'infection', text: 'A keylogger is secretly installed on a computer, often via phishing.', microcopy: 'The keylogger is installed.' },
      { time: 3, label: 'typing', text: 'The user types a username and password into a website.', microcopy: 'The user logs in.' },
      { time: 6, label: 'recording', text: 'Every keystroke is silently recorded by the keylogger program.', microcopy: 'Every key press is being recorded!' },
      { time: 9, label: 'theft', text: 'The log of keystrokes, including the password, is sent to the hacker.', microcopy: 'Your password has been stolen!' },
      { time: 12, label: 'defense', text: 'Using an on-screen keyboard can sometimes bypass hardware keyloggers.', microcopy: 'On-screen keyboards can help.' },
    ],
    defenses: [
        { point: 'Keep Antivirus Updated', description: 'Many security programs can detect and block known keyloggers.' },
        { point: 'Use Two-Factor Authentication (2FA)', description: 'Even if a hacker steals your password, they won\'t have your 2FA code.' },
        { point: 'Be Careful on Public Computers', description: 'Avoid logging into sensitive accounts on library or school computers.' },
    ],
    quiz: {
      question: 'What specific information is a keylogger designed to steal?',
      options: ['Your computer\'s location', 'Your files', 'What you type, like passwords and messages', 'Your computer\'s brand name'],
      correctAnswer: 'What you type, like passwords and messages',
      explanation: 'Keyloggers are specifically focused on capturing keyboard inputs to steal credentials and other sensitive typed information.',
    },
    miniSim: {
      description: 'You have to log into your email on a public computer. What is the safest action?',
      options: [
        { id: 'a', text: 'Type your password as usual.', isCorrect: false },
        { id: 'b', text: 'Change your password immediately after you are done.', isCorrect: false },
        { id: 'c', 'text': 'Don\'t log in. Wait until you can use a trusted device.', isCorrect: true },
      ],
      feedback: {
        correct: 'That\'s the most secure choice. You can never be sure if a public computer is clean from malware like keyloggers.',
        incorrect: 'Even changing your password after doesn\'t help if the keylogger steals the new one, too! The safest option is to avoid it.',
      },
    },
    funFact: 'Keyloggers can be either software programs or small hardware devices that plug in between the keyboard and the computer.',
    badge: 'Keystroke Guardian',
  },
  {
    id: 'social',
    title: 'Social Engineering',
    simpleDefinition: 'Tricking people into doing things or giving away information.',
    kidFriendly: "Like a trickster convincing someone to hand over their homework.",
    animationSteps: [
      { time: 0, label: 'impersonation', text: 'An attacker calls, pretending to be from tech support.', microcopy: 'A call from "Tech Support".', focusPoint: {x: 40, y: 100} },
      { time: 3, label: 'urgency', text: 'They create a sense of urgency, saying there is a problem that needs to be fixed now.', microcopy: '"There\'s a problem with your account!"', focusPoint: {x: 130, y: 60} },
      { time: 6, label: 'request', text: 'They ask the user for their password to "fix" the problem.', microcopy: '"I need your password to help."', focusPoint: {x: 340, y: 100} },
      { time: 9, label: 'deception', text: 'The user gives the password, and the attacker now has access.', microcopy: 'The attacker now has the password!', focusPoint: { x: 300, y: 100 } },
      { time: 12, label: 'defense', text: 'The user gets suspicious, hangs up, and calls the official tech support number to verify.', microcopy: 'Always verify independently!', focusPoint: { x: 270, y: 50 } },
    ],
    defenses: [
        { point: 'Be Skeptical', description: 'Be wary of unsolicited calls or messages, especially if they ask for personal info.' },
        { point: 'Verify Independently', description: 'Hang up and call the organization back using their official phone number.' },
        { point: 'Never Share Passwords or OTPs', description: 'Legitimate companies will never ask for your password or One-Time Passcodes.' },
    ],
    quiz: {
      question: 'If someone from "tech support" calls and asks for your password, what should you do?',
      options: ['Give it to them so they can help', 'Ask them to prove who they are', 'Hang up and call the real tech support number', 'Ask them to call back later'],
      correctAnswer: 'Hang up and call the real tech support number',
      explanation: 'The safest action is to end the conversation and initiate contact yourself through a trusted, official channel.',
    },
    miniSim: {
      description: 'You get a text from a friend asking you to send them money for an emergency. It sounds a little strange. What do you do?',
      options: [
        { id: 'a', text: 'Send the money right away.', isCorrect: false },
        { id: 'b', text: 'Text back asking for more proof.', isCorrect: false },
        { id: 'c', text: 'Call your friend on their usual number to check if it\'s really them.', isCorrect: true },
      ],
      feedback: {
        correct: 'Yes! Calling them is the best way to verify it\'s a real emergency and not an attacker who has taken over their account.',
        incorrect: 'Replying or sending money could be a mistake. It\'s best to verify by calling them directly.',
      },
    },
    funFact: 'One of the most famous hackers, Kevin Mitnick, was a master of social engineering and often said it was his most effective tool.',
    badge: 'Human Firewall',
  },
  {
    id: 'insider',
    title: 'Insider Threat',
    simpleDefinition: 'Someone inside an organization misuses their access, on purpose or by accident.',
    kidFriendly: "Like a teammate taking extra snacks from the team box just because they can.",
    animationSteps: [
      { time: 0, label: 'authorized-access', text: 'An employee has access to sensitive company files as part of their job.', microcopy: 'An employee with normal access.' },
      { time: 3, label: 'misuse', text: 'They decide to copy all the files to a personal USB drive before leaving the company.', microcopy: 'Copying files to a personal device.' },
      { time: 6, label: 'data-exfiltration', text: 'The sensitive data is removed from the company\'s secure network.', microcopy: 'Data is leaving the network!' },
      { time: 9, label: 'damage', text: 'The company\'s secrets are now at risk of being exposed or sold.', microcopy: 'The company is now at risk.' },
      { time: 12, label: 'defense', text: 'Monitoring software detects the large file transfer and alerts security.', microcopy: 'An alert is triggered by the unusual activity.' },
    ],
    defenses: [
        { point: 'Least Privilege', description: 'Only give employees access to the specific data they need for their job.' },
        { point: 'Monitoring', description: 'Log and monitor access to sensitive files for unusual activity.' },
        { point: 'Security Awareness Training', description: 'Train employees on security policies and the risks of data theft.' },
    ],
    quiz: {
      question: 'What is the "Principle of Least Privilege"?',
      options: ['Give everyone access to everything', 'Give people the minimum access they need to do their job', 'The person with the least work gets the most privileges', 'Privileges are not allowed'],
      correctAnswer: 'Give people the minimum access they need to do their job',
      explanation: 'This principle is a key defense against insider threats, as it limits the amount of damage a single compromised or malicious account can do.',
    },
    miniSim: {
      description: 'A coworker from another department asks you to email them a sensitive file they don\'t have access to. What do you do?',
      options: [
        { id: 'a', text: 'Email it to them to be helpful.', isCorrect: false },
        { id: 'b', text: 'Tell them to ask their manager to request official access.', isCorrect: true },
        { id: 'c', text: 'Ignore their request.', isCorrect: false },
      ],
      feedback: {
        correct: 'Correct. Directing them through official channels ensures there is a record and proper authorization for access.',
        incorrect: 'Sharing data with unauthorized people, even coworkers, can be a security risk. It\'s better to follow official procedures.',
      },
    },
    funFact: 'Studies show that a significant percentage of data breaches involve an insider, whether their actions were malicious or purely accidental.',
    badge: 'Access Guardian',
  },
  {
    id: 'supplychain',
    title: 'Supply Chain Attack',
    simpleDefinition: 'A trusted tool or update is infected, which then spreads to everyone who uses it.',
    kidFriendly: "Like a tainted ingredient from a supplier that spoils all the lunches in the cafeteria.",
    animationSteps: [
      { time: 0, label: 'trusted-vendor', text: 'A company uses a popular software tool from a trusted vendor.', microcopy: 'A trusted software vendor.' },
      { time: 3, label: 'vendor-breach', text: 'An attacker hacks the vendor and secretly adds malicious code to the software.', microcopy: 'The vendor is hacked!' },
      { time: 6, label: 'malicious-update', text: 'The vendor releases a new update, not knowing it contains the malicious code.', microcopy: 'A tainted update is sent out.' },
      { time: 9, label: 'widespread-infection', text: 'All the companies using the software install the update, unknowingly infecting themselves.', microcopy: 'The infection spreads to all customers!' },
      { time: 12, label: 'defense', text: 'A code signing verification check fails, warning that the update has been tampered with.', microcopy: 'A digital signature check can detect tampering.' },
    ],
    defenses: [
        { point: 'Vendor Risk Checks', description: 'Companies should carefully evaluate the security of their software suppliers.' },
        { point: 'Validate Code Signing', description: 'Ensure that software updates have a valid digital signature from the vendor.' },
        { point: 'Network Segmentation', description: 'Isolating critical systems can prevent a breach in one area from spreading.' },
    ],
    quiz: {
      question: 'In a supply chain attack, who is the initial target of the hackers?',
      options: ['The end user', 'The software vendor or supplier', 'The government', 'The internet provider'],
      correctAnswer: 'The software vendor or supplier',
      explanation: 'The goal is to compromise a trusted supplier to use their distribution network as a way to attack all their customers.',
    },
    miniSim: {
      description: 'You get an update notification for a tool you use, but your security software says the "digital signature is invalid". What do you do?',
      options: [
        { id: 'a', text: 'Install it anyway, it\'s probably a mistake.', isCorrect: false },
        { id: 'b', text: 'Do not install it and report the warning.', isCorrect: true },
        { id: 'c', text: 'Find a different link to download the update.', isCorrect: false },
      ],
      feedback: {
        correct: 'Excellent. An invalid signature is a major red flag that the software may have been tampered with.',
        incorrect: 'An invalid signature warning should never be ignored. It is a critical security check.',
      },
    },
    funFact: 'The infamous SolarWinds attack was a sophisticated supply chain attack that affected major corporations and government agencies worldwide.',
    badge: 'Chain Checker',
  },
  {
    id: 'zeroday',
    title: 'Zero-Day Exploit',
    simpleDefinition: 'An attack that uses a software bug that nobody knows how to fix yet.',
    kidFriendly: "Like finding a secret hidden door that even the teachers didn\'t know about.",
    animationSteps: [
      { time: 0, label: 'software-vulnerability', text: 'A piece of software has an unknown bug or flaw.', microcopy: 'A hidden flaw in the code.' },
      { time: 3, label: 'discovery', text: 'An attacker discovers the flaw before the software creators do.', microcopy: 'An attacker finds the flaw.' },
      { time: 6, label: 'exploit', text: 'The attacker uses the flaw to break into the system.', microcopy: 'The secret flaw is exploited!' },
      { time: 9, label: 'no-defense', text: 'Because the flaw is unknown, traditional antivirus may not detect the attack.', microcopy: 'There is no patch yet!' },
      { time: 12, label: 'defense', text: 'An emergency patch is released and applied, closing the vulnerability.', microcopy: 'A patch is released to fix the flaw.' },
    ],
    defenses: [
        { point: 'Patch Quickly', description: 'Apply security patches as soon as they become available.' },
        { point: 'Intrusion Detection Systems (IDS)', description: 'These systems can sometimes spot suspicious behavior even from a zero-day attack.' },
        { point: 'Use Sandboxing', description: 'Running risky applications in an isolated "sandbox" can contain any damage.' },
    ],
    quiz: {
      question: 'Why is it called a "zero-day" attack?',
      options: ['It always happens at midnight', 'It costs zero dollars to perform', 'The developers have had "zero days" to fix the problem', 'It only infects computers with zero files'],
      correctAnswer: 'The developers have had "zero days" to fix the problem',
      explanation: 'The term refers to the fact that the vulnerability is discovered and exploited on the same day, giving developers no time to create a patch.',
    },
    miniSim: {
      description: 'A critical zero-day vulnerability is announced for your web browser. A patch is available. What should you do?',
      options: [
        { id: 'a', text: 'Wait a week to see if the patch is stable.', isCorrect: false },
        { id: 'b', text: 'Apply the patch immediately.', isCorrect: true },
        { id: 'c', text: 'Switch to a different browser forever.', isCorrect: false },
      ],
      feedback: {
        correct: 'Absolutely. For critical security flaws, the best defense is to patch as quickly as possible.',
        incorrect: 'Waiting to patch a known, critical vulnerability leaves you exposed to attack.',
      },
    },
    funFact: 'The Stuxnet computer worm, which targeted industrial control systems, is famous for using multiple different zero-day exploits.',
    badge: 'Patch Pioneer',
  },
  {
    id: 'databreach',
    title: 'Data Breach',
    simpleDefinition: 'When sensitive information is stolen from a system by an unauthorized person.',
    kidFriendly: "Like a thief breaking into the school's filing cabinet and taking everyone's report cards.",
    animationSteps: [
      { time: 0, label: 'server', text: 'A company server securely stores user data.', microcopy: 'Data is stored securely.' },
      { time: 3, label: 'vulnerability-exploited', text: 'An attacker finds and exploits a weakness in the server\'s security.', microcopy: 'A weakness is found.' },
      { time: 6, label: 'data-exfiltration', text: 'The attacker copies large amounts of user data from the server.', microcopy: 'Data is being stolen!' },
      { time: 9, label: 'data-leaked', text: 'The stolen data is transferred to the attacker\'s own server.', microcopy: 'The data is now in the wrong hands.' },
      { time: 12, label: 'defense', text: 'Strong encryption makes the stolen data unreadable and useless to the attacker.', microcopy: 'Encryption scrambles the data.' },
    ],
    defenses: [
        { point: 'Use Strong Passwords', description: 'Use unique passwords for every online account to limit damage if one site is breached.' },
        { point: 'Share Minimal Data', description: 'Only provide personal information to websites that you trust and that truly need it.' },
        { point: 'Enable Breach Alerts', description: 'Use services that notify you if your email address appears in a known data breach.' },
    ],
    quiz: {
      question: 'What is the best way to protect your other accounts if one website you use has a data breach?',
      options: ['Delete your account on that website', 'Hope the hackers don\'t find your data', 'Having a unique password for that site', 'Emailing the website to complain'],
      correctAnswer: 'Having a unique password for that site',
      explanation: 'If you use unique passwords, even if one is stolen, the hackers can\'t use it to get into your other accounts.',
    },
    miniSim: {
      description: 'You are signing up for a new game. Which information is safest to share?',
      options: [
        { id: 'a', text: 'Your full name, real birthday, and home address.', isCorrect: false },
        { id: 'b', text: 'Just a username and a unique password.', isCorrect: true },
        { id: 'c', text: 'Your email and your school\'s name.', isCorrect: false },
      ],
      feedback: {
        correct: 'Perfect! The less personal data you share, the less there is to lose in a data breach.',
        incorrect: 'Sharing too much personal information online can be risky. Only provide what is absolutely necessary.',
      },
    },
    funFact: 'Many of the largest data breaches in history were caused by simple human error, not super-advanced hacking.',
    badge: 'Data Guardian',
  },
  {
    id: 'spoofing',
    title: 'Fake Websites (Spoofing)',
    simpleDefinition: 'Creating a fake website that looks like a real one to trick people into entering their login details.',
    kidFriendly: "It's like a fake candy store that looks exactly like your favorite one, but it's run by a monster.",
    animationSteps: [
      { time: 0, label: 'fake-url', text: 'A user receives a link to a website, but the URL is slightly misspelled.', microcopy: 'Check the URL carefully.' },
      { time: 3, label: 'identical-site', text: 'The website looks exactly like the real login page the user trusts.', microcopy: 'It looks real, but is it?' },
      { time: 6, label: 'login-attempt', text: 'The user types their username and password into the fake site.', microcopy: 'The user enters their password.' },
      { time: 9, label: 'credential-theft', text: 'The login details are sent directly to the attacker, not the real website.', microcopy: 'The password is stolen!' },
      { time: 12, label: 'defense', text: 'The browser warns the user that the site is not secure (no HTTPS) and is a known phishing site.', microcopy: 'Browser warnings can protect you.' },
    ],
    defenses: [
        { point: 'Check the Domain Name', description: 'Carefully check the URL for spelling mistakes (e.g., "gogle.com" instead of "google.com").' },
        { point: 'Look for HTTPS', description: 'Legitimate sites that handle sensitive data use HTTPS, shown by a padlock icon in the address bar.' },
        { point: 'Use a Password Manager', description: 'Password managers often won\'t autofill on a fake domain, which can be a good warning sign.' },
    ],
    quiz: {
      question: 'What is one of the biggest clues that a website might be a fake (spoofed)?',
      options: ['It has a lot of pictures', 'The colors are slightly different', 'The URL has a small spelling error', 'It loads very fast'],
      correctAnswer: 'The URL has a small spelling error',
      explanation: 'Attackers often register domain names that are very close to the real one, hoping users won\'t notice the difference.',
    },
    miniSim: {
      description: 'Which of these links is most likely the real one?',
      options: [
        { id: 'a', text: 'www.mybank.com', isCorrect: true },
        { id: 'b', text: 'www.my-bank.login.com', isCorrect: false },
        { id: 'c', text: 'www.mybanc.com', isCorrect: false },
      ],
      feedback: {
        correct: 'You got it! The others use tricks like subdomains or misspellings to fool you.',
        incorrect: 'Look closely at the spelling and structure. Fake sites often use small tricks to look legitimate.',
      },
    },
    funFact: 'This is also called "website spoofing". The same idea can be applied to email and phone calls, called "email spoofing" and "caller ID spoofing".',
    badge: 'URL Inspector',
  },
  {
    id: 'clickjacking',
    title: 'Clickjacking',
    simpleDefinition: 'Tricking a user into clicking something different from what they perceive, potentially revealing confidential information.',
    kidFriendly: "It's like a magician hiding a 'delete homework' button underneath a 'play game' button.",
    animationSteps: [
      { time: 0, label: 'visible-button', text: 'A user sees a fun button on a webpage, like "Play Video".', microcopy: 'This looks like a normal button.' },
      { time: 3, label: 'hidden-layer', text: 'An invisible, malicious button is placed directly on top of the visible one.', microcopy: 'There\'s a hidden layer!' },
      { time: 6, label: 'user-click', text: 'The user thinks they are clicking "Play Video".', microcopy: 'The user clicks.' },
      { time: 9, label: 'hijacked-click', text: 'Their click is actually registered on the invisible button, performing a hidden action.', microcopy: 'The click did something else!' },
      { time: 12, label: 'defense', text: 'Modern browsers have built-in protections to prevent pages from being loaded in invisible frames.', microcopy: 'Browser security helps prevent this.' },
    ],
    defenses: [
        { point: 'Keep Your Browser Updated', description: 'Browser developers are constantly adding new security features to combat threats like clickjacking.' },
        { point: 'Use Browser Security Extensions', description: 'Some extensions can provide extra protection by blocking scripts from untrusted sites.' },
        { point: 'Be Cautious of Suspicious Pop-ups', description: 'If a button or link seems out of place, it\'s best not to click it.' },
    ],
    quiz: {
      question: 'In a clickjacking attack, what is the user tricked into doing?',
      options: ['Downloading a virus', 'Clicking on something they can\'t see', 'Entering their password', 'Turning off their computer'],
      correctAnswer: 'Clicking on something they can\'t see',
      explanation: 'The attack works by hijacking a click and directing it to a hidden, malicious element on the page.',
    },
    miniSim: {
      description: 'A pop-up appears with a giant "Claim Your Prize!" button, but it looks a bit unprofessional. What do you do?',
      options: [
        { id: 'a', text: 'Click the button to see what the prize is.', isCorrect: false },
        { id: 'b', text: 'Try to find the small "X" to close the pop-up instead of clicking the main button.', isCorrect: true },
      ],
      feedback: {
        correct: 'Wise choice. Safely closing unexpected windows is much better than clicking on potentially hijacked buttons.',
        incorrect: 'That\'s risky! The button could be a trap. It\'s safer to close the window.',
      },
    },
    funFact: 'An early version of this attack was used against the Adobe Flash plugin settings page, tricking users into turning on their webcams.',
    badge: 'Click Commander',
  },
  {
    id: 'rootkit',
    title: 'Rootkit',
    simpleDefinition: 'A type of malware designed to hide itself deep inside a computer\'s operating system.',
    kidFriendly: "It's like an invisible monster that hides in the school's basement, making it very hard for the principal to find.",
    animationSteps: [
      { time: 0, label: 'infection', text: 'A rootkit infects the core of the computer\'s operating system.', microcopy: 'Infecting the system core.' },
      { time: 3, label: 'concealment', text: 'The rootkit actively hides its own files and processes from the user.', microcopy: 'The malware is now hidden.' },
      { time: 6, label: 'antivirus-scan', text: 'A normal antivirus scan runs, but it can\'t see the hidden rootkit.', microcopy: 'A normal scan can\'t find it!' },
      { time: 9, label: 'malicious-activity', text: 'The hidden rootkit gives an attacker complete control over the computer.', microcopy: 'The hacker has full control.' },
      { time: 12, label: 'defense', text: 'A specialized rootkit scanner or a system reboot can sometimes detect and remove it.', microcopy: 'Special tools are needed.' },
    ],
    defenses: [
        { point: 'Keep Your System Updated', description: 'OS updates often patch the vulnerabilities that rootkits use to get in.' },
        { point: 'Don\'t Ignore Security Warnings', description: 'Be careful when granting administrator or "root" permissions to programs.' },
        { point: 'Use Specialized Scanners', description: 'If you suspect a rootkit, use anti-rootkit tools or boot-time scans.' },
    ],
    quiz: {
      question: 'What is the main goal of a rootkit?',
      options: ['To show you ads', 'To lock your files', 'To hide its presence on the computer', 'To slow down your internet'],
      correctAnswer: 'To hide its presence on the computer',
      explanation: 'Rootkits are all about stealth. They modify the operating system to become invisible, allowing them to persist for a long time without being detected.',
    },
    miniSim: {
      description: 'You are about to install a program, and it asks for "Administrator" or "Root" access. You don\'t know the program well. What\'s the safest choice?',
      options: [
        { id: 'a', text: 'Grant the access to make sure it works properly.', isCorrect: false },
        { id: 'b', text: 'Deny the access. If you don\'t trust it, don\'t give it the highest permissions.', isCorrect: true },
      ],
      feedback: {
        correct: 'Excellent decision. Granting root access is like giving someone the master key to your house. Only do it for software you completely trust.',
        incorrect: 'Giving a program root access is very risky. A malicious program with these permissions could install a rootkit.',
      },
    },
    funFact: 'The "root" in rootkit comes from the name for the most powerful user account on Unix and Linux operating systems.',
    badge: 'System Sentinel',
  },
];